apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ihl5fifod-dotnet-basic 
  janus-idp.io/tekton: ihl5fifod-dotnet-basic
  backstage.io/kubernetes-id: ihl5fifod-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ihl5fifod-dotnet-basic
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml